/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Circuito_Sum (
  input A,
  input B,
  output Y,
  output X
);
  assign Y = (A & B);
  assign X = (B ^ A);
endmodule
